version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    labels:
      - "cleanup-no-release-required"
      - "dependencies"
      - "github_actions"

  - package-ecosystem: "npm"
    directory: "/www/scripts/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    versioning-strategy: "increase"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    versioning-strategy: "increase"
    allow:
      - dependency-type: "all"
