<?php

namespace Curl;

abstract class Options {

    /**
     * @var array[string] Associative Array of Curl Options and their Human Readable forms.
     * @see toHuman()
     */
    private static $map = array(
        CURLOPT_AUTOREFERER => 'CURLOPT_AUTOREFERER',
        CURLOPT_BINARYTRANSFER => 'CURLOPT_BINARYTRANSFER',
        CURLOPT_COOKIESESSION => 'CURLOPT_COOKIESESSION',
        CURLOPT_CERTINFO => 'CURLOPT_CERTINFO',
        CURLOPT_CONNECT_ONLY => 'CURLOPT_CONNECT_ONLY',
        CURLOPT_CRLF => 'CURLOPT_CRLF',
        CURLOPT_DNS_USE_GLOBAL_CACHE => 'CURLOPT_DNS_USE_GLOBAL_CACHE',
        CURLOPT_FAILONERROR => 'CURLOPT_FAILONERROR',
        CURLOPT_FILETIME => 'CURLOPT_FILETIME',
        CURLOPT_FOLLOWLOCATION => 'CURLOPT_FOLLOWLOCATION',
        CURLOPT_FORBID_REUSE => 'CURLOPT_FORBID_REUSE',
        CURLOPT_FRESH_CONNECT => 'CURLOPT_FRESH_CONNECT',
        CURLOPT_FTP_USE_EPRT => 'CURLOPT_FTP_USE_EPRT',
        CURLOPT_FTP_USE_EPSV => 'CURLOPT_FTP_USE_EPSV',
        CURLOPT_FTP_CREATE_MISSING_DIRS => 'CURLOPT_FTP_CREATE_MISSING_DIRS',
        CURLOPT_FTPAPPEND => 'CURLOPT_FTPAPPEND',
        CURLOPT_TCP_NODELAY => 'CURLOPT_TCP_NODELAY',
        CURLOPT_FTPASCII => 'CURLOPT_FTPASCII',
        CURLOPT_FTPLISTONLY => 'CURLOPT_FTPLISTONLY',
        CURLOPT_HEADER => 'CURLOPT_HEADER',
        CURLINFO_HEADER_OUT => 'CURLINFO_HEADER_OUT',
        CURLOPT_HTTPGET => 'CURLOPT_HTTPGET',
        CURLOPT_HTTPPROXYTUNNEL => 'CURLOPT_HTTPPROXYTUNNEL',
        CURLOPT_MUTE => 'CURLOPT_MUTE',
        CURLOPT_NETRC => 'CURLOPT_NETRC',
        CURLOPT_NOBODY => 'CURLOPT_NOBODY',
        CURLOPT_NOPROGRESS => 'CURLOPT_NOPROGRESS',
        CURLOPT_NOSIGNAL => 'CURLOPT_NOSIGNAL',
        CURLOPT_POST => 'CURLOPT_POST',
        CURLOPT_PUT => 'CURLOPT_PUT',
        CURLOPT_RETURNTRANSFER => 'CURLOPT_RETURNTRANSFER',
        CURLOPT_SAFE_UPLOAD => 'CURLOPT_SAFE_UPLOAD',
        CURLOPT_SSL_VERIFYPEER => 'CURLOPT_SSL_VERIFYPEER',
        CURLOPT_TRANSFERTEXT => 'CURLOPT_TRANSFERTEXT',
        CURLOPT_UNRESTRICTED_AUTH => 'CURLOPT_UNRESTRICTED_AUTH',
        CURLOPT_UPLOAD => 'CURLOPT_UPLOAD',
        CURLOPT_VERBOSE => 'CURLOPT_VERBOSE',
        CURLOPT_BUFFERSIZE => 'CURLOPT_BUFFERSIZE',
        CURLOPT_CLOSEPOLICY => 'CURLOPT_CLOSEPOLICY',
        CURLOPT_CONNECTTIMEOUT => 'CURLOPT_CONNECTTIMEOUT',
        CURLOPT_CONNECTTIMEOUT_MS => 'CURLOPT_CONNECTTIMEOUT_MS',
        CURLOPT_DNS_CACHE_TIMEOUT => 'CURLOPT_DNS_CACHE_TIMEOUT',
        CURLOPT_FTPSSLAUTH => 'CURLOPT_FTPSSLAUTH',
        CURLOPT_HTTP_VERSION => 'CURLOPT_HTTP_VERSION',
        CURLOPT_HTTPAUTH => 'CURLOPT_HTTPAUTH',
        CURLOPT_INFILESIZE => 'CURLOPT_INFILESIZE',
        CURLOPT_LOW_SPEED_LIMIT => 'CURLOPT_LOW_SPEED_LIMIT',
        CURLOPT_LOW_SPEED_TIME => 'CURLOPT_LOW_SPEED_TIME',
        CURLOPT_MAXCONNECTS => 'CURLOPT_MAXCONNECTS',
        CURLOPT_MAXREDIRS => 'CURLOPT_MAXREDIRS',
        CURLOPT_PORT => 'CURLOPT_PORT',
        CURLOPT_PROTOCOLS => 'CURLOPT_PROTOCOLS',
        CURLOPT_PROXYAUTH => 'CURLOPT_PROXYAUTH',
        CURLOPT_PROXYPORT => 'CURLOPT_PROXYPORT',
        CURLOPT_PROXYTYPE => 'CURLOPT_PROXYTYPE',
        CURLOPT_REDIR_PROTOCOLS => 'CURLOPT_REDIR_PROTOCOLS',
        CURLOPT_RESUME_FROM => 'CURLOPT_RESUME_FROM',
        CURLOPT_SSL_VERIFYHOST => 'CURLOPT_SSL_VERIFYHOST',
        CURLOPT_SSLVERSION => 'CURLOPT_SSLVERSION',
        CURLOPT_TIMECONDITION => 'CURLOPT_TIMECONDITION',
        CURLOPT_TIMEOUT => 'CURLOPT_TIMEOUT',
        CURLOPT_TIMEOUT_MS => 'CURLOPT_TIMEOUT_MS',
        CURLOPT_TIMEVALUE => 'CURLOPT_TIMEVALUE',
        CURLOPT_MAX_RECV_SPEED_LARGE => 'CURLOPT_MAX_RECV_SPEED_LARGE',
        CURLOPT_MAX_SEND_SPEED_LARGE => 'CURLOPT_MAX_SEND_SPEED_LARGE',
        CURLOPT_SSH_AUTH_TYPES => 'CURLOPT_SSH_AUTH_TYPES',
        CURLOPT_IPRESOLVE => 'CURLOPT_IPRESOLVE',
        CURLOPT_CAINFO => 'CURLOPT_CAINFO',
        CURLOPT_CAPATH => 'CURLOPT_CAPATH',
        CURLOPT_COOKIE => 'CURLOPT_COOKIE',
        CURLOPT_COOKIEFILE => 'CURLOPT_COOKIEFILE',
        CURLOPT_COOKIEJAR => 'CURLOPT_COOKIEJAR',
        CURLOPT_CUSTOMREQUEST => 'CURLOPT_CUSTOMREQUEST',
        CURLOPT_EGDSOCKET => 'CURLOPT_EGDSOCKET',
        CURLOPT_ENCODING => 'CURLOPT_ENCODING',
        CURLOPT_FTPPORT => 'CURLOPT_FTPPORT',
        CURLOPT_INTERFACE => 'CURLOPT_INTERFACE',
        CURLOPT_KEYPASSWD => 'CURLOPT_KEYPASSWD',
        CURLOPT_KRB4LEVEL => 'CURLOPT_KRB4LEVEL',
        CURLOPT_POSTFIELDS => 'CURLOPT_POSTFIELDS',
        CURLOPT_PROXY => 'CURLOPT_PROXY',
        CURLOPT_PROXYUSERPWD => 'CURLOPT_PROXYUSERPWD',
        CURLOPT_RANDOM_FILE => 'CURLOPT_RANDOM_FILE',
        CURLOPT_RANGE => 'CURLOPT_RANGE',
        CURLOPT_REFERER => 'CURLOPT_REFERER',
        CURLOPT_SSH_HOST_PUBLIC_KEY_MD5 => 'CURLOPT_SSH_HOST_PUBLIC_KEY_MD5',
        CURLOPT_SSH_PUBLIC_KEYFILE => 'CURLOPT_SSH_PUBLIC_KEYFILE',
        CURLOPT_SSH_PRIVATE_KEYFILE => 'CURLOPT_SSH_PRIVATE_KEYFILE',
        CURLOPT_SSL_CIPHER_LIST => 'CURLOPT_SSL_CIPHER_LIST',
        CURLOPT_SSLCERT => 'CURLOPT_SSLCERT',
        CURLOPT_SSLCERTPASSWD => 'CURLOPT_SSLCERTPASSWD',
        CURLOPT_SSLCERTTYPE => 'CURLOPT_SSLCERTTYPE',
        CURLOPT_SSLENGINE => 'CURLOPT_SSLENGINE',
        CURLOPT_SSLENGINE_DEFAULT => 'CURLOPT_SSLENGINE_DEFAULT',
        CURLOPT_SSLKEY => 'CURLOPT_SSLKEY',
        CURLOPT_SSLKEYPASSWD => 'CURLOPT_SSLKEYPASSWD',
        CURLOPT_SSLKEYTYPE => 'CURLOPT_SSLKEYTYPE',
        CURLOPT_URL => 'CURLOPT_URL',
        CURLOPT_USERAGENT => 'CURLOPT_USERAGENT',
        CURLOPT_USERPWD => 'CURLOPT_USERPWD',
        CURLOPT_HTTP200ALIASES => 'CURLOPT_HTTP200ALIASES',
        CURLOPT_HTTPHEADER => 'CURLOPT_HTTPHEADER',
        CURLOPT_POSTQUOTE => 'CURLOPT_POSTQUOTE',
        CURLOPT_QUOTE => 'CURLOPT_QUOTE',
        CURLOPT_FILE => 'CURLOPT_FILE',
        CURLOPT_INFILE => 'CURLOPT_INFILE',
        CURLOPT_STDERR => 'CURLOPT_STDERR',
        CURLOPT_WRITEHEADER => 'CURLOPT_WRITEHEADER',
        CURLOPT_HEADERFUNCTION => 'CURLOPT_HEADERFUNCTION',
        CURLOPT_PASSWDFUNCTION => 'CURLOPT_PASSWDFUNCTION',
        CURLOPT_PROGRESSFUNCTION => 'CURLOPT_PROGRESSFUNCTION',
        CURLOPT_READFUNCTION => 'CURLOPT_READFUNCTION',
        CURLOPT_WRITEFUNCTION => 'CURLOPT_WRITEFUNCTION',
        CURLOPT_SHARE => 'CURLOPT_SHARE',
    );

    /**
     * Human
     *
     * @param int $option Curl Option
     *
     * @return string It's Human Readable Form
     *
     * @static
     * @access public
     *
     * @author Michael Mulligan <michael@bigroomstudios.com>
     */
    public static function human($option) {
        return (string) (isset(self::$map[$option]) ? self::$map[$option] : $option);
    }

}